//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanerApp_Table
    {
        public int BanerId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> Position { get; set; }
        public Nullable<int> SupeerId { get; set; }
    
        public virtual Supper_Table Supper_Table { get; set; }
    }
}
