//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Table
    {
        public int ContactId { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Tele { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Map { get; set; }
        public string Logo { get; set; }
        public string Whustup { get; set; }
        public string Telegram { get; set; }
        public string Insta { get; set; }
        public string Twiter { get; set; }
        public string Facebook { get; set; }
    }
}
