//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Following_Table
    {
        public int FollowingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SupperId { get; set; }
        public Nullable<System.DateTime> DateFollow { get; set; }
    
        public virtual Supper_Table Supper_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
