//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_Table()
        {
            this.SlideMenu_Table = new HashSet<SlideMenu_Table>();
            this.Supper_Table = new HashSet<Supper_Table>();
        }
    
        public int MenuId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Kind { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> OrderItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideMenu_Table> SlideMenu_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supper_Table> Supper_Table { get; set; }
    }
}
