//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Table()
        {
            this.OrderDetail_Table = new HashSet<OrderDetail_Table>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<int> SupperId { get; set; }
        public Nullable<System.DateTime> DateSales { get; set; }
        public string FactorCode { get; set; }
        public Nullable<bool> KindOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CopenId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual User_Table User_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail_Table> OrderDetail_Table { get; set; }
    }
}
