//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail_Table
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductShopId { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Order_Table Order_Table { get; set; }
        public virtual Product_Table Product_Table { get; set; }
        public virtual ProductShop_Table ProductShop_Table { get; set; }
    }
}
