//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class People_Table
    {
        public int PeopleId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Tele { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DareRequestLa { get; set; }
    }
}
