//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Table()
        {
            this.Like_Table = new HashSet<Like_Table>();
            this.OrderDetail_Table = new HashSet<OrderDetail_Table>();
            this.OwnerProduct_Table = new HashSet<OwnerProduct_Table>();
            this.Review_Table = new HashSet<Review_Table>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Imageurl { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public Nullable<bool> StateIndex { get; set; }
        public string Images { get; set; }
        public string attributes { get; set; }
        public Nullable<int> EbazaarProductID { get; set; }
        public Nullable<int> StateShop { get; set; }
        public Nullable<bool> Haraji { get; set; }
        public Nullable<System.DateTime> EndHaraji { get; set; }
        public Nullable<bool> StateOff { get; set; }
        public Nullable<int> OffPresent { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Kind { get; set; }
        public Nullable<int> LikePro { get; set; }
        public Nullable<int> DisLikePro { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
        public virtual Group_Table Group_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_Table> Like_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail_Table> OrderDetail_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerProduct_Table> OwnerProduct_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review_Table> Review_Table { get; set; }
    }
}
