//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShop_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductShop_Table()
        {
            this.OrderDetail_Table = new HashSet<OrderDetail_Table>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Name { get; set; }
        public string Imageurl { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public string Images { get; set; }
        public string attributes { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> LikePro { get; set; }
        public Nullable<int> DisLikePro { get; set; }
    
        public virtual GroupShop_Table GroupShop_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail_Table> OrderDetail_Table { get; set; }
    }
}
