//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideMenu_Table
    {
        public int SlideMenuId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Imageurl { get; set; }
    
        public virtual Menu_Table Menu_Table { get; set; }
    }
}
