//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story_Table
    {
        public int StoryId { get; set; }
        public Nullable<int> PeopleId { get; set; }
        public Nullable<bool> StateUser { get; set; }
        public Nullable<bool> StateShow { get; set; }
        public string ImageUrl { get; set; }
    }
}
