//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supper_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supper_Table()
        {
            this.BanerApp_Table = new HashSet<BanerApp_Table>();
            this.Delivery_Table = new HashSet<Delivery_Table>();
            this.Following_Table = new HashSet<Following_Table>();
            this.Like_Table = new HashSet<Like_Table>();
            this.OwenerGroup_Table = new HashSet<OwenerGroup_Table>();
            this.OwnerProduct_Table = new HashSet<OwnerProduct_Table>();
        }
    
        public int SupperId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Logo { get; set; }
        public Nullable<int> KindHaHo { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<bool> Married { get; set; }
        public Nullable<bool> Melliat { get; set; }
        public string SodorIdentyNo { get; set; }
        public string MelliCode { get; set; }
        public string IdentyNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> ProvinceFaaliat { get; set; }
        public Nullable<int> Education { get; set; }
        public string Major { get; set; }
        public Nullable<int> Javaz { get; set; }
        public string JavazNo { get; set; }
        public string CompanyName { get; set; }
        public string SabtNo { get; set; }
        public Nullable<System.DateTime> SabtDate { get; set; }
        public string MahaleSabt { get; set; }
        public string ShenasehMelli { get; set; }
        public string CodeEghtesadi { get; set; }
        public string MobileCodeHaghighi { get; set; }
        public string Tele { get; set; }
        public string ShopName { get; set; }
        public string Sheba { get; set; }
        public string HandicraftsGroups { get; set; }
        public string GroupsKanons { get; set; }
        public Nullable<bool> AnbarState { get; set; }
        public string AnbarTele { get; set; }
        public string AnbarAddress { get; set; }
        public Nullable<int> CompanyKind { get; set; }
        public Nullable<int> KindFaaliat { get; set; }
        public string SahebanEmza { get; set; }
        public Nullable<int> CountShop { get; set; }
        public string Address { get; set; }
        public string Dastgah { get; set; }
        public string KarmandNo { get; set; }
        public string Place { get; set; }
        public Nullable<int> IsargariStatus { get; set; }
        public string PostOrgin { get; set; }
        public string IdentityPostOrgin { get; set; }
        public string VahedOrgin { get; set; }
        public string IdentityVahedOrgin { get; set; }
        public string JobName { get; set; }
        public string JobTabagheh { get; set; }
        public string JobRotbeh { get; set; }
        public Nullable<System.DateTime> KhedmatDate { get; set; }
        public Nullable<System.DateTime> SabeghehDate { get; set; }
        public string PlaceKhedmat { get; set; }
        public Nullable<int> CityKhedmat { get; set; }
        public string Mojavez1 { get; set; }
        public string Mojavez2 { get; set; }
        public string Mojavez3 { get; set; }
        public string Mojavez4 { get; set; }
        public string Mojavez5 { get; set; }
        public string Mojavez6 { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NewsPassword { get; set; }
        public Nullable<bool> StatueActive { get; set; }
        public Nullable<bool> StatusPanel { get; set; }
        public string whatsup { get; set; }
        public string instagram { get; set; }
        public string telegram { get; set; }
        public string MyLat { get; set; }
        public string MyLot { get; set; }
        public Nullable<int> LikeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanerApp_Table> BanerApp_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Table> Delivery_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Following_Table> Following_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_Table> Like_Table { get; set; }
        public virtual Menu_Table Menu_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwenerGroup_Table> OwenerGroup_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerProduct_Table> OwnerProduct_Table { get; set; }
        public virtual Region_Table Region_Table { get; set; }
    }
}
