//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme_Table
    {
        public int ThemeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> TagId { get; set; }
        public string Banner1 { get; set; }
        public string Banner2 { get; set; }
        public Nullable<int> BannerGroup1 { get; set; }
        public Nullable<int> BannerGroup2 { get; set; }
        public Nullable<int> LayoutCat1 { get; set; }
        public Nullable<int> LayoutCat2 { get; set; }
    }
}
