//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironika_Theme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Total
    {
        public int OrderId { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<System.DateTime> DateSales { get; set; }
        public Nullable<int> Status { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> SupperId { get; set; }
    }
}
